spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Register & Login Route
        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/auth/**

        # User-Management Service Route
        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: portfolio-management
          uri: lb://PORTFOLIO-MANAGEMENT
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8088